apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-gitactions-testing
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: temp-gitactions-testing
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9090
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9090
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            limits:
              cpu: "400m"
              memory: "575Mi"
            requests:
              cpu: "12m"
              memory: "512Mi"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "prod"
