              port: 9090
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
                cpu: "12m"
                memory: "128Mi"
            limits:
                cpu: "400m"
                memory: "512Mi"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "nonprod"
