apiVersion: apps/v1
kind: Deployment
metadata:
  name:  temp-gitactions-testing
spec:
    matchLabels:
  template:
    metadata:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9090
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9090
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
          ports:
            - name: actuator
              containerPort: 9090
              protocol: TCP
            - name: http
              containerPort: 9095
              protocol: TCP
          resources:
            requests:
              cpu: "{{ .Values.requests.cpu }}"
              memory: "{{ .Values.requests.memory }}"
            limits:
              cpu: "{{ .Values.limits.cpu }}"
              memory: "{{ .Values.limits.memory }}"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              valueFrom:
                secretKeyRef:
                  key: value
                  name: profile-setting
            - name: kv-client-id
              valueFrom:
                secretKeyRef:
                  name: test-kv-secret
                  key: kv-client-id
            - name: kv-client-key
              valueFrom:
                secretKeyRef:
                  name: test-kv-secret
                  key: kv-client-key
            - name: kv-tenant-id
              valueFrom:
                secretKeyRef:
                  name: test-kv-secret
                  key: kv-tenant-id
            - name: kv-uri
              valueFrom:
                secretKeyRef:
                  name: test-kv-secret
                  key: kv-uri
