apiVersion: v1
kind: Service
metadata:
  name:  temp-gitactions-testing
spec:
  type: ClusterIP
  ports:
    - port: 9095
      protocol: TCP
      name: http
  selector:
    app: temp-gitactions-testing
    type: orchestrator
    version: 1.0.0
