apiVersion: v1
kind: Service
metadata:
  name:  {{ include "temp-gitactions-testing.fullname" . }}
  labels:
    app: temp-gitactions-testing
    type: orchestrator
    version: 1.0.0
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9095
      protocol: TCP
      name: http
  selector:
    app: temp-gitactions-testing
    type: orchestrator
    version: 1.0.0
